### ISSUE TITLE
msvc2019, audioDevice.cpp find error

### ISSUE THREAD

**Issue by libaineu2004** [cross-platform/dspatchables#10]
Using msvc2019 to compile the source code, an error will be reported:

Severity Code Description The project file line does not display status
Error C2039 "replace_if":  It's not "std."  Member AudioDevice E:\dspatcher\dspatcher-master\DSPatchables\Components\AudioDevice\ audioDevice.cpp  68

Here's my solution:
Add a header file to audioDevice.cpp
#include < algorithm>

**Comment by MarcusTomlinson** [comment]
Thanks for letting me know! Fixed now
